site_name: pafnuty
repo_url: https://github.com/yannmclatchie/pafnuty

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Overview: 'index.md'
  - Tutorials:
    - Disc sampling: notebooks/01-ym-disc-sampling.ipynb
  - api_docs.md
  - changelog.md

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true

plugins:
  - search:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
  - mknotebooks:
